[package]
name = "coaptic"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["Jeff Glousher"]
license = "MIT OR Apache-2.0"
description = "Stand-alone no_std CoAP engine"
repository = "https://github.com/jeffglousher/coaptic"
readme = "README.md"
categories = ["no-std", "embedded", "network-programming"]
keywords = ["coap", "no-std", "embedded", "no-alloc"]

[features]
default = []
alloc = []
std = ["alloc"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "udp_engine"
required-features = ["std"]
