//! [`Response`]: owned intent that [`App`](super::App) encodes into TX,
//! and the owned snapshot [`App::take_response`](super::App::take_response)
//! yields for a completed client [`Call`](super::Call).

use crate::message::{
    Code, ContentFormat, Echo, MessageId, MissingBlocks, ProblemDetails, Token, Type,
};
use crate::storage::{Endpoint, MemoryProfile};

/// Bytes copied into a [`Response`] when the payload is not `'static`.
pub const INLINE_PAYLOAD: usize = 128;

/// Cap for assembled client Block2 bodies (not a field of [`Response`];
/// see [`super::App::take_response`]). Also the ceiling for
/// [`super::link_format_capacity`] / [`super::LinkFormatScratch`].
pub const RESPONSE_BODY: usize = 4096;

/// Maximum Location-Path or Location-Query values a [`Response`] can carry.
///
/// Same bound as [`super::MAX_PATH_SEGMENTS`]. Extra values passed to
/// [`Response::location_path`] / [`Response::location_query`] are ignored.
pub const LOCATION_MAX: usize = 8;

#[derive(Clone, Copy, Debug)]
enum Payload<'a> {
    Empty,
    Static(&'static [u8]),
    Inline {
        bytes: [u8; INLINE_PAYLOAD],
        len: u16,
    },
    /// Catalog or other generated bytes that outlive this [`Response`]
    /// (poll / [`LinkFormatScratch`](super::LinkFormatScratch)). Not an
    /// owned 4KiB field.
    Borrowed(&'a [u8]),
}

/// Conversion into a [`Response`].
///
/// Stored handlers are [`fn(Request<'_>) -> Response`](super::HandlerFn).
/// Implement this if a wrapper type should become a response.
pub trait IntoResponse {
    /// Build the response.
    fn into_response(self) -> Response<'static>;
}

impl IntoResponse for Response<'static> {
    fn into_response(self) -> Response<'static> {
        self
    }
}

/// Owned response: handler intent, or a client snapshot from
/// [`App::take_response`](super::App::take_response).
///
/// One type on both faces. Handlers return this; [`App::poll`](super::App::poll)
/// encodes it (one datagram, or Block2 / Q-Block2 from the TX body when
/// the payload is large). Handlers do not opt in and do not see slot
/// identifiers.
///
/// A completed [`Call`](super::Call) is the same type: [`Self::code`] /
/// [`Self::payload`] (this datagram, truncated at [`INLINE_PAYLOAD`], or a
/// borrowed catalog) / [`Self::body`] (assembled Block2 / Q-Block2,
/// borrowed from [`super::App`] until the next `take_response` / `poll`) /
/// [`Self::problem_details`] / [`Self::missing_block_nums`]. Snapshot
/// [`Self::ty`] / [`Self::token`] / [`Self::peer`] are `Some` after a
/// completed client exchange. A 2.01 Created can carry
/// [`Self::location_path`] / [`Self::location_query`] (bounded, `'static`,
/// no heap). [`Self::separate`] is an empty ACK to a CON request, then the
/// representation in a later CON (new Message ID).
///
/// The type does **not** own `[u8; RESPONSE_BODY]`. Handler returns and
/// [`Self::observe`] copy the small header + inline/`'static` payload only.
///
/// ```
/// use coaptic::{ContentFormat, Response};
///
/// let response = Response::content(b"21.5").content_format(ContentFormat::TEXT_PLAIN);
/// assert_eq!(response.code(), coaptic::Code::CONTENT);
/// assert_eq!(response.payload(), b"21.5");
/// ```
#[derive(Clone, Copy, Debug)]
pub struct Response<'a> {
    code: Code,
    payload: Payload<'a>,
    content_format: Option<ContentFormat>,
    etag: [u8; 8],
    etag_len: u8,
    max_age: Option<u32>,
    observe: Option<u32>,
    ty: Option<Type>,
    token: Option<Token>,
    mid: Option<MessageId>,
    peer: Option<Endpoint>,
    assembled: Option<&'a [u8]>,
    echo: Option<Echo>,
    location_path: [&'static str; LOCATION_MAX],
    location_path_len: u8,
    location_query: [&'static str; LOCATION_MAX],
    location_query_len: u8,
    separate: bool,
}

impl<'a> Response<'a> {
    /// Response with `code` and no payload.
    #[must_use]
    pub const fn new(code: Code) -> Self {
        Self {
            code,
            payload: Payload::Empty,
            content_format: None,
            etag: [0; 8],
            etag_len: 0,
            max_age: None,
            observe: None,
            ty: None,
            token: None,
            mid: None,
            peer: None,
            assembled: None,
            echo: None,
            location_path: [""; LOCATION_MAX],
            location_path_len: 0,
            location_query: [""; LOCATION_MAX],
            location_query_len: 0,
            separate: false,
        }
    }

    /// 2.05 Content with a `'static` payload.
    #[must_use]
    pub const fn content(payload: &'static [u8]) -> Self {
        Self::new(Code::CONTENT).with_static(payload)
    }

    /// 2.05 Content, copying `payload` into the inline buffer (truncated at
    /// [`INLINE_PAYLOAD`]).
    #[must_use]
    pub fn content_copy(payload: &[u8]) -> Self {
        Self::new(Code::CONTENT).payload_copy(payload)
    }

    /// 2.01 Created.
    ///
    /// Attach the new resource with [`Self::location_path`] /
    /// [`Self::location_query`].
    #[must_use]
    pub const fn created() -> Self {
        Self::new(Code::CREATED)
    }

    /// 2.02 Deleted.
    #[must_use]
    pub const fn deleted() -> Self {
        Self::new(Code::DELETED)
    }

    /// 2.03 Valid.
    #[must_use]
    pub const fn valid() -> Self {
        Self::new(Code::VALID)
    }

    /// 2.04 Changed.
    #[must_use]
    pub const fn changed() -> Self {
        Self::new(Code::CHANGED)
    }

    /// 4.00 Bad Request.
    #[must_use]
    pub const fn bad_request() -> Self {
        Self::new(Code::BAD_REQUEST)
    }

    /// 4.01 Unauthorized.
    #[must_use]
    pub const fn unauthorized() -> Self {
        Self::new(Code::UNAUTHORIZED)
    }

    /// 4.03 Forbidden.
    #[must_use]
    pub const fn forbidden() -> Self {
        Self::new(Code::FORBIDDEN)
    }

    /// 4.04 Not Found.
    #[must_use]
    pub const fn not_found() -> Self {
        Self::new(Code::NOT_FOUND)
    }

    /// 4.05 Method Not Allowed.
    #[must_use]
    pub const fn method_not_allowed() -> Self {
        Self::new(Code::METHOD_NOT_ALLOWED)
    }

    /// 4.12 Precondition Failed.
    #[must_use]
    pub const fn precondition_failed() -> Self {
        Self::new(Code::PRECONDITION_FAILED)
    }

    /// 4.15 Unsupported Content-Format.
    #[must_use]
    pub const fn unsupported_content_format() -> Self {
        Self::new(Code::UNSUPPORTED_CONTENT_FORMAT)
    }

    /// 5.00 Internal Server Error.
    #[must_use]
    pub const fn internal_error() -> Self {
        Self::new(Code::INTERNAL_SERVER_ERROR)
    }

    /// 5.01 Not Implemented.
    #[must_use]
    pub const fn not_implemented() -> Self {
        Self::new(Code::NOT_IMPLEMENTED)
    }

    /// 5.03 Service Unavailable.
    #[must_use]
    pub const fn service_unavailable() -> Self {
        Self::new(Code::SERVICE_UNAVAILABLE)
    }

    /// Client or server error with RFC 9290 concise problem details (CBOR).
    ///
    /// Sets Content-Format to [`ContentFormat::PROBLEM_DETAILS`] (257) and a
    /// CBOR map that includes `response-code` (−4) equal to `code`. Title
    /// and detail are optional ([`Self::title`], [`Self::detail`]). Named
    /// builders such as [`Self::not_found`] stay empty; call this when a
    /// structured body is wanted. [`App`](super::App) uses this for
    /// generated 4.04 / 4.05, apply-error 4.08, and 4.01 when Echo
    /// freshness is on. Progress-driven Q-Block1 holes use
    /// [`Self::missing_blocks`] instead.
    ///
    /// Override the Content-Format with [`Self::content_format`] only when
    /// the peer asked for something else.
    ///
    /// ```
    /// use coaptic::{Code, ContentFormat, ProblemDetails, Response};
    ///
    /// let response = Response::problem(Code::NOT_FOUND).title("Not Found");
    /// assert_eq!(response.code(), Code::NOT_FOUND);
    /// assert_eq!(response.format(), Some(ContentFormat::PROBLEM_DETAILS));
    /// let details = ProblemDetails::decode(response.payload()).expect("cbor");
    /// assert_eq!(details.response_code(), Some(Code::NOT_FOUND));
    /// assert_eq!(details.title_text(), Some("Not Found"));
    /// ```
    #[must_use]
    pub fn problem(code: Code) -> Self {
        Self::new(code).with_problem(None, None)
    }

    /// 4.08 with RFC 9177 missing-blocks CBOR-seq (Content-Format 272).
    ///
    /// Encodes `nums` as a CBOR Sequence of unsigned integers (no array
    /// wrapper). [`App`](super::App) uses this for progress-driven Q-Block1
    /// holes. Apply errors and other 4.08 stay [`Self::problem`].
    ///
    /// ```
    /// use coaptic::{Code, ContentFormat, Response};
    ///
    /// let response = Response::missing_blocks([1, 9]);
    /// assert_eq!(response.code(), Code::REQUEST_ENTITY_INCOMPLETE);
    /// assert_eq!(response.format(), Some(ContentFormat::MISSING_BLOCKS));
    /// let mut nums = [0u32; 4];
    /// assert_eq!(response.missing_block_nums(&mut nums), Some(&[1, 9][..]));
    /// ```
    #[must_use]
    pub fn missing_blocks(nums: impl IntoIterator<Item = u32>) -> Self {
        let mut buf = [0u8; INLINE_PAYLOAD];
        match MissingBlocks::encode(nums, &mut buf) {
            Ok(n) => Self::new(Code::REQUEST_ENTITY_INCOMPLETE)
                .content_format(ContentFormat::MISSING_BLOCKS)
                .payload_copy(&buf[..n]),
            Err(_) => Self::new(Code::REQUEST_ENTITY_INCOMPLETE)
                .content_format(ContentFormat::MISSING_BLOCKS),
        }
    }

    /// Decode the payload as RFC 9177 missing-blocks NUMs when the
    /// Content-Format is [`ContentFormat::MISSING_BLOCKS`].
    #[must_use]
    pub fn missing_block_nums<'n>(&self, out: &'n mut [u32]) -> Option<&'n [u32]> {
        if self.content_format != Some(ContentFormat::MISSING_BLOCKS) {
            return None;
        }
        let n = MissingBlocks::decode(self.payload(), out).ok()?;
        Some(&out[..n])
    }

    /// Set the RFC 9290 title (−1) and keep (or set) problem-details CBOR.
    #[must_use]
    pub fn title(self, title: &str) -> Self {
        let mut detail_buf = [0u8; INLINE_PAYLOAD];
        let detail = copy_problem_field(self.problem_field(Field::Detail), &mut detail_buf);
        self.with_problem(Some(title), detail)
    }

    /// Set the RFC 9290 detail (−2) and keep (or set) problem-details CBOR.
    #[must_use]
    pub fn detail(self, detail: &str) -> Self {
        let mut title_buf = [0u8; INLINE_PAYLOAD];
        let title = copy_problem_field(self.problem_field(Field::Title), &mut title_buf);
        self.with_problem(title, Some(detail))
    }

    /// Decode the payload as RFC 9290 problem details when the Content-Format
    /// is [`ContentFormat::PROBLEM_DETAILS`].
    #[must_use]
    pub fn problem_details(&self) -> Option<ProblemDetails<'_>> {
        if self.content_format != Some(ContentFormat::PROBLEM_DETAILS) {
            return None;
        }
        ProblemDetails::decode(self.payload()).ok()
    }

    fn problem_field(&self, field: Field) -> Option<&str> {
        let parsed = ProblemDetails::decode(self.payload()).ok()?;
        match field {
            Field::Title => parsed.title_text(),
            Field::Detail => parsed.detail_text(),
        }
    }

    fn with_problem(mut self, title: Option<&str>, detail: Option<&str>) -> Self {
        self.content_format = Some(
            self.content_format
                .unwrap_or(ContentFormat::PROBLEM_DETAILS),
        );
        self.payload = encode_problem_payload(self.code, title, detail);
        self
    }

    /// Set Content-Format.
    #[must_use]
    pub const fn content_format(mut self, format: ContentFormat) -> Self {
        self.content_format = Some(format);
        self
    }

    /// Set ETag (1–8 bytes; longer values are truncated).
    #[must_use]
    pub fn etag(mut self, etag: &[u8]) -> Self {
        let n = etag.len().min(8);
        self.etag[..n].copy_from_slice(&etag[..n]);
        self.etag_len = n as u8;
        self
    }

    /// Set the Echo option (RFC 9175).
    ///
    /// [`App::poll`](super::App::poll) writes this on a freshness 4.01.
    #[must_use]
    pub const fn echo(mut self, echo: Echo) -> Self {
        self.echo = Some(echo);
        self
    }

    /// Echo option, if set.
    #[must_use]
    pub const fn echo_option(&self) -> Option<Echo> {
        self.echo
    }

    /// Set Max-Age in seconds.
    #[must_use]
    pub const fn max_age(mut self, seconds: u32) -> Self {
        self.max_age = Some(seconds);
        self
    }

    /// Append a Location-Path segment.
    ///
    /// Empty segments and values past [`LOCATION_MAX`] are ignored.
    /// [`App::poll`](super::App::poll) writes these on the wire.
    ///
    /// ```
    /// use coaptic::Response;
    ///
    /// let response = Response::created()
    ///     .location_path("location1")
    ///     .location_path("location2");
    /// assert_eq!(response.location_paths(), &["location1", "location2"]);
    /// ```
    #[must_use]
    pub const fn location_path(mut self, segment: &'static str) -> Self {
        if segment.is_empty() {
            return self;
        }
        let n = self.location_path_len as usize;
        if n < LOCATION_MAX {
            self.location_path[n] = segment;
            self.location_path_len += 1;
        }
        self
    }

    /// Append a Location-Query value.
    ///
    /// Empty values and values past [`LOCATION_MAX`] are ignored.
    ///
    /// ```
    /// use coaptic::Response;
    ///
    /// let response = Response::created()
    ///     .location_query("first=1")
    ///     .location_query("second=2");
    /// assert_eq!(response.location_queries(), &["first=1", "second=2"]);
    /// ```
    #[must_use]
    pub const fn location_query(mut self, query: &'static str) -> Self {
        if query.is_empty() {
            return self;
        }
        let n = self.location_query_len as usize;
        if n < LOCATION_MAX {
            self.location_query[n] = query;
            self.location_query_len += 1;
        }
        self
    }

    /// Location-Path segments in insertion order.
    #[must_use]
    pub fn location_paths(&self) -> &[&str] {
        &self.location_path[..usize::from(self.location_path_len)]
    }

    /// Location-Query values in insertion order.
    #[must_use]
    pub fn location_queries(&self) -> &[&str] {
        &self.location_query[..usize::from(self.location_query_len)]
    }

    /// Send as a separate response (RFC 7252 §5.2.2).
    ///
    /// A CON request is acknowledged with an empty ACK; the representation
    /// follows in a new CON with a fresh Message ID and the request Token.
    /// A NON request is answered with a NON that also uses a fresh Message
    /// ID. [`App::poll`](super::App::poll) performs both sends. Default is
    /// piggybacked ACK (CON) or a NON that reuses the request Message ID.
    ///
    /// ```
    /// use coaptic::Response;
    ///
    /// let response = Response::content(b"later").separate();
    /// assert!(response.is_separate());
    /// ```
    #[must_use]
    pub const fn separate(mut self) -> Self {
        self.separate = true;
        self
    }

    /// Whether [`Self::separate`] was set.
    #[must_use]
    pub const fn is_separate(&self) -> bool {
        self.separate
    }

    /// Set Observe sequence.
    ///
    /// On a successful GET/FETCH with Observe=0 this opts the handler into
    /// registration ([`App`](super::App) writes sequence 0 on the wire).
    /// [`App::notify`](super::App::notify) overwrites this with the table
    /// sequence. Mutating in place avoids copying the payload.
    #[must_use]
    pub const fn observe(mut self, sequence: u32) -> Self {
        self.set_observe(sequence);
        self
    }

    /// Write Observe sequence without moving `self`.
    pub const fn set_observe(&mut self, sequence: u32) {
        self.observe = Some(sequence);
    }

    /// Drop Observe so a registration miss cannot claim success on the wire.
    ///
    /// RFC 7641 §4.1: if the interest cannot be stored, the response is sent
    /// as if Observe had not been requested.
    #[must_use]
    pub const fn without_observe(mut self) -> Self {
        self.observe = None;
        self
    }

    /// Replace the payload with a `'static` slice.
    #[must_use]
    pub const fn with_static(mut self, payload: &'static [u8]) -> Self {
        self.payload = if payload.is_empty() {
            Payload::Empty
        } else {
            Payload::Static(payload)
        };
        self
    }

    /// Replace the payload by copying into the inline buffer.
    #[must_use]
    pub fn payload_copy(mut self, payload: &[u8]) -> Self {
        let n = payload.len().min(INLINE_PAYLOAD);
        let mut bytes = [0u8; INLINE_PAYLOAD];
        bytes[..n].copy_from_slice(&payload[..n]);
        self.payload = if n == 0 {
            Payload::Empty
        } else {
            Payload::Inline {
                bytes,
                len: n as u16,
            }
        };
        self
    }

    /// Use `payload` as the body without copying (catalog / poll scratch).
    ///
    /// Lengths that fit inline use [`Self::payload_copy`]. Larger slices are
    /// borrowed for `'a`.
    #[must_use]
    pub fn payload_copy_full(self, payload: &'a [u8]) -> Self {
        if payload.len() <= INLINE_PAYLOAD {
            return self.payload_copy(payload);
        }
        let n = payload.len().min(RESPONSE_BODY);
        let mut response = self;
        response.payload = Payload::Borrowed(&payload[..n]);
        response
    }

    /// Response code.
    #[must_use]
    pub const fn code(&self) -> Code {
        self.code
    }

    /// Payload bytes.
    #[must_use]
    pub fn payload(&self) -> &[u8] {
        match self.payload {
            Payload::Empty => &[],
            Payload::Static(bytes) => bytes,
            Payload::Inline { ref bytes, len } => &bytes[..usize::from(len)],
            Payload::Borrowed(bytes) => bytes,
        }
    }

    /// Content-Format, if set.
    #[must_use]
    pub const fn format(&self) -> Option<ContentFormat> {
        self.content_format
    }

    /// ETag, if set.
    #[must_use]
    pub fn etag_bytes(&self) -> Option<&[u8]> {
        if self.etag_len == 0 {
            None
        } else {
            Some(&self.etag[..usize::from(self.etag_len)])
        }
    }

    /// Max-Age seconds, if set.
    #[must_use]
    pub const fn max_age_secs(&self) -> Option<u32> {
        self.max_age
    }

    /// Observe sequence, if set (handler intent or a client snapshot).
    #[must_use]
    pub const fn observe_seq(&self) -> Option<u32> {
        self.observe
    }

    /// CON / NON / ACK / RST on a client snapshot, if [`App::take_response`](super::App::take_response)
    /// populated it.
    #[must_use]
    pub const fn ty(&self) -> Option<Type> {
        self.ty
    }

    /// Token on a client snapshot, if populated (same as [`Call::token`](super::Call::token)).
    #[must_use]
    pub const fn token(&self) -> Option<Token> {
        self.token
    }

    /// Message ID of the matched datagram on a client snapshot, if populated.
    #[must_use]
    pub const fn message_id(&self) -> Option<MessageId> {
        self.mid
    }

    /// Remote endpoint that sent a client-snapshot response, if populated.
    #[must_use]
    pub const fn peer(&self) -> Option<Endpoint> {
        self.peer
    }

    /// Complete assembled response body, if Block2 / Q-Block2 filled an RX body area.
    ///
    /// `None` when this is handler intent or a single-datagram client
    /// snapshot. Borrowed from [`super::App`] after [`super::App::take_response`]
    /// (truncated at [`RESPONSE_BODY`]). Invalidated by a later take or poll.
    #[must_use]
    pub const fn body(&self) -> Option<&'a [u8]> {
        self.assembled
    }

    /// Whether [`Self::body`] is present (including an empty complete body).
    #[must_use]
    pub const fn has_body(&self) -> bool {
        self.assembled.is_some()
    }

    pub(crate) fn from_client(
        code: Code,
        ty: Type,
        token: Token,
        mid: MessageId,
        peer: Endpoint,
        payload: &[u8],
        content_format: Option<ContentFormat>,
    ) -> Self {
        let mut response = Self::new(code).payload_copy(payload);
        response.content_format = content_format;
        response.ty = Some(ty);
        response.token = Some(token);
        response.mid = Some(mid);
        response.peer = Some(peer);
        response
    }

    pub(crate) fn with_assembled(mut self, src: &'a [u8]) -> Self {
        self.assembled = Some(src);
        self
    }
}

#[derive(Clone, Copy)]
enum Field {
    Title,
    Detail,
}

fn copy_problem_field<'a>(src: Option<&str>, buf: &'a mut [u8]) -> Option<&'a str> {
    let text = src?;
    if text.len() > buf.len() {
        return None;
    }
    buf[..text.len()].copy_from_slice(text.as_bytes());
    core::str::from_utf8(&buf[..text.len()]).ok()
}

fn encode_problem_payload(
    code: Code,
    title: Option<&str>,
    detail: Option<&str>,
) -> Payload<'static> {
    let attempts = [(title, detail), (title, None), (None, None)];
    let mut buf = [0u8; INLINE_PAYLOAD];
    for (title, detail) in attempts {
        let mut details = ProblemDetails::new(code);
        if let Some(title) = title {
            details = details.title(title);
        }
        if let Some(detail) = detail {
            details = details.detail(detail);
        }
        if let Ok(n) = details.encode(&mut buf) {
            let mut bytes = [0u8; INLINE_PAYLOAD];
            bytes[..n].copy_from_slice(&buf[..n]);
            return Payload::Inline {
                bytes,
                len: n as u16,
            };
        }
    }
    Payload::Empty
}

/// Scratch for [`super::App::take_response`] assembled Block2 bodies.
///
/// One App-owned hold (not a field of [`Response`]). Handler returns and
/// Observe sequence updates copy the small [`Response`] header only.
/// Datagram App (`BLOCK_WISE = false`) uses [`AssembledNone`] (ZST).
pub(crate) trait AssembledBytes {
    /// Copy `src` (truncated at [`RESPONSE_BODY`]).
    fn store(&mut self, src: &[u8]);
    /// Held bytes after [`Self::store`].
    ///
    /// [`AssembledBuf`]: `len == 0` (never stored, or stored empty) returns
    /// `Some(&[])`. Empty and unset are not distinguished.
    /// [`AssembledNone`]: always `None`.
    fn view(&self) -> Option<&[u8]>;
}

/// ZST stand-in: `.block_wise::<false>()` has no client Block2 hold.
#[derive(Default)]
#[doc(hidden)]
pub struct AssembledNone;

impl AssembledBytes for AssembledNone {
    fn store(&mut self, _src: &[u8]) {}

    fn view(&self) -> Option<&[u8]> {
        None
    }
}

/// Owned [`RESPONSE_BODY`] hold for a completed client Block2 / Q-Block2 body.
///
/// Not `Copy`: `[u8; RESPONSE_BODY]` would memcpy 4KiB on every assign.
#[doc(hidden)]
pub struct AssembledBuf {
    bytes: [u8; RESPONSE_BODY],
    len: u16,
}

impl Default for AssembledBuf {
    fn default() -> Self {
        Self {
            bytes: [0u8; RESPONSE_BODY],
            len: 0,
        }
    }
}

impl AssembledBytes for AssembledBuf {
    fn store(&mut self, src: &[u8]) {
        let n = src.len().min(RESPONSE_BODY);
        self.bytes[..n].copy_from_slice(&src[..n]);
        self.len = n as u16;
    }

    fn view(&self) -> Option<&[u8]> {
        Some(&self.bytes[..usize::from(self.len)])
    }
}

/// Selects [`AssembledNone`] or [`AssembledBuf`] from `BLOCK_WISE`.
///
/// Bound on [`super::App`] so the hold is a ZST when `BLOCK_WISE` is false.
/// Blanket-implemented for every [`MemoryProfile`].
#[doc(hidden)]
pub trait AppAssembled<const BLOCK_WISE: bool> {
    /// [`AssembledNone`] or [`AssembledBuf`].
    #[doc(hidden)]
    type Buf: Default;

    /// Copy `src` into the hold (no-op on the datagram stub).
    #[doc(hidden)]
    fn store(buf: &mut Self::Buf, src: &[u8]);

    /// Held bytes: [`AssembledBuf`] returns `Some` even when `len == 0`;
    /// [`AssembledNone`] returns `None`.
    #[doc(hidden)]
    fn view(buf: &Self::Buf) -> Option<&[u8]>;
}

impl<P: MemoryProfile> AppAssembled<false> for P {
    type Buf = AssembledNone;

    fn store(buf: &mut Self::Buf, src: &[u8]) {
        buf.store(src);
    }

    fn view(buf: &Self::Buf) -> Option<&[u8]> {
        buf.view()
    }
}

impl<P: MemoryProfile> AppAssembled<true> for P {
    type Buf = AssembledBuf;

    fn store(buf: &mut Self::Buf, src: &[u8]) {
        buf.store(src);
    }

    fn view(buf: &Self::Buf) -> Option<&[u8]> {
        buf.view()
    }
}

pub(crate) type AssembledField<P, const BLOCK_WISE: bool> = <P as AppAssembled<BLOCK_WISE>>::Buf;

#[cfg(test)]
mod assembled_hold_tests {
    use super::{AppAssembled, AssembledBuf, AssembledBytes, AssembledNone, RESPONSE_BODY};
    use crate::profiles;
    use core::mem::size_of;

    #[test]
    fn datagram_assembled_hold_is_zst() {
        assert_eq!(
            size_of::<<profiles::Default as AppAssembled<false>>::Buf>(),
            0
        );
        assert_eq!(size_of::<AssembledNone>(), 0);
        assert!(size_of::<<profiles::Default as AppAssembled<true>>::Buf>() >= RESPONSE_BODY);
        assert!(size_of::<AssembledBuf>() >= RESPONSE_BODY);
    }

    #[test]
    fn assembled_buf_view_empty_and_unset_are_some() {
        let unset = AssembledBuf::default();
        assert_eq!(unset.view(), Some(&[][..]));
        let mut stored_empty = AssembledBuf::default();
        stored_empty.store(&[]);
        assert_eq!(stored_empty.view(), Some(&[][..]));
        let mut none = AssembledNone;
        assert_eq!(none.view(), None);
        none.store(b"x");
        assert_eq!(none.view(), None);
    }
}
